version: '3'
services:
  postgres12:
    image: postgres:12
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_PASSWORD: 'prisma'
    ports:
      - '5434:5432'
    networks:
      - databases

networks:
  databases: null
